"""Initial migration

Revision ID: ab927e2e840d
Revises: 
Create Date: 2026-02-05 06:44:25.212667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ab927e2e840d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('route_data', 'position_ts',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('route_data', 'route_status_ts',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('route_data', 'student_status_ts',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('route_data', 'student_status_ts',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('route_data', 'route_status_ts',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('route_data', 'position_ts',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
